events {}

http {
    server {
        listen 80;

        # [M11] Leaks Nginx version number in error pages
        server_tokens on; 

        # [FIX 2] Set root to the mounted source code
        root /app_code;

        location / {
            # Check if file exists in /app_code first (.env), else go to backend
            try_files $uri @backend;
            
            # [M7] CORS Wildcard (Duplicate of application layer, but also bad here)
            add_header 'Access-Control-Allow-Origin' '*';
            
            # [M8] MISSING: X-Content-Type-Options, HSTS, CSP are NOT here.
        }

        location @backend {
            proxy_pass http://backend:8000;
        }

        # [M3] Directory listing enabled on /uploads
        location /uploads {
            alias /app/uploads;
            autoindex on; 
        }

        # [M4] Sensitive files like .env are explicitly ALLOWED
        location ~ /\.(env|git|db) {
            allow all; 
        }
    }
}
